running kubeadm join only if worker node is not already joined

diff --git a/.github/workflows/deploy-kubernetes-app.yml b/.github/workflows/deploy-kubernetes-app.yml
--- a/.github/workflows/deploy-kubernetes-app.yml
+++ b/.github/workflows/deploy-kubernetes-app.yml
@@ -144,12 +144,33 @@ jobs:
             # Get the join command
             JOIN_COMMAND=$(kubeadm token create --print-join-command)
             echo "Join command: ${JOIN_COMMAND}"
-
+      
             # Store the command in a file on the master server
             echo "sudo ${JOIN_COMMAND}" > /tmp/join_command.sh
             chmod +x /tmp/join_command.sh  # Make it executable
-
+      
+      - name: Check Worker Node Registration
+        id: check_worker_registration
+        uses: appleboy/ssh-action@v0.1.5
+        with:
+          host: ${{ env.MASTER_INSTANCE_PUBLIC_IP }}  # Connect to master first
+          username: ${{ secrets.SERVER_USER }}
+          key: ${{ secrets.SERVER_SSH_KEY }}
+          script: |
+            WORKER_IP=${{ env.WORKER_INSTANCE_PUBLIC_IP }}
+            echo "Checking if the worker node is already registered..."
+      
+            # Check if the worker node is listed
+            if kubectl get nodes | grep $WORKER_IP; then
+              echo "Node $WORKER_IP is already registered."
+              exit 0  # Exit with status 0, indicating success without action
+            else
+              echo "Node $WORKER_IP is not registered. Proceeding with join command."
+              exit 1  # Exit with a non-zero status to continue to the join step
+            fi
+      
       - name: Join Worker Node to Cluster
+        if: steps.check_worker_registration.outcome == 'failure'  # Only run if the previous step failed (node not registered)
         uses: appleboy/ssh-action@v0.1.5
         with:
           host: ${{ env.MASTER_INSTANCE_PUBLIC_IP }}  # Connect to master first
@@ -157,16 +178,16 @@ jobs:
           key: ${{ secrets.SERVER_SSH_KEY }}
           script: |
             echo "Joining the worker node to the cluster..."
-
+      
             # Create a temporary key file
             echo "${{ secrets.SERVER_SSH_KEY }}" > /tmp/private_key
             chmod 600 /tmp/private_key  # Ensure it's only readable by the user
-
+      
             # Copy the join command script to the worker node
             scp -o StrictHostKeyChecking=no -i /tmp/private_key /tmp/join_command.sh ubuntu@${{ env.WORKER_INSTANCE_PUBLIC_IP }}:/tmp/
-
+      
             # SSH to the worker node and run the join command
-            ssh -o StrictHostKeyChecking=no -i /tmp/private_key ubuntu@${{ env.WORKER_INSTANCE_PUBLIC_IP }} "bash /tmp/join_command.sh"     
+            ssh -o StrictHostKeyChecking=no -i /tmp/private_key ubuntu@${{ env.WORKER_INSTANCE_PUBLIC_IP }} "bash /tmp/join_command.sh"
 
       - name: Completion Script echo Master Server url
         uses: appleboy/ssh-action@v0.1.5
